### ISSUE TITLE
No output debug file

### ISSUE THREAD

**Issue by stef-pellegrino** [pleriche/FastMM5#3]
With a simple VCL app on Windows 10, Delphi 10.3
FastMM5 in the first .pas in .dpr

...But no output file is generated at the end, when the app is closed !??

**Comment by pleriche** [comment]
Hi Stephane,

All event messages in FastMM5 can either be displayed on the screen, logged to file, sent to the debugger, or any combination of the three. By default, memory leak events are not routed anywhere.

In order to log them to file, place the following code somewhere in your application:
FastMM_LogToFileEvents := FastMM_LogToFileEvents + [mmetUnexpectedMemoryLeakDetail, mmetUnexpectedMemoryLeakSummary];

Best regards,
Pierre

**Comment by stef-pellegrino** [comment]
Hi Pierre, thanks for the answer... 👍 
I'm supposed to read the doc ;) but I was assuming -wrongly- that the behavior was the same than FastMM4... 
Ok, to make it short : My fault
